name: Deploy Flutter Web para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar para Web
        run: flutter build web --base-href "/controle-de-ponto/"

      - name: Publicar no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages
